### ISSUE TITLE
overwrite=True as default?

### ISSUE THREAD

**Issue by guettli** [shawalli/psycopg2-pgevents#14]
If you would ask me, then I would use overwrite=True as default.

It can cost you a lot of time to find the error why something is not working, and then you realize that
you used the old trigger.

**Comment by shawalli** [comment]
When originally writing this library, I considered `overwrite` as analogous to `force`. In my opinion, `force` or destructive settings should always be opt-in rather than opt-out.

**Comment by shawalli** [comment]
Closing due to age of last comment.
